//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo.Blazor.Reports.PivotGridAndChart
{

    public partial class Report : DevExpress.XtraReports.UI.XtraReport {
        private void InitializeComponent() {
            DevExpress.XtraReports.ReportInitializer reportInitializer = new DevExpress.XtraReports.ReportInitializer(this, "BlazorDemo.Reporting.Reports.PivotGridAndChart.Report.repx");

            // Controls
            this.Detail = reportInitializer.GetControl<DevExpress.XtraReports.UI.DetailBand>("Detail");
            this.BottomMargin = reportInitializer.GetControl<DevExpress.XtraReports.UI.BottomMarginBand>("BottomMargin");
            this.topMarginBand1 = reportInitializer.GetControl<DevExpress.XtraReports.UI.TopMarginBand>("topMarginBand1");
            this.ReportHeader = reportInitializer.GetControl<DevExpress.XtraReports.UI.ReportHeaderBand>("ReportHeader");
            this.xrChart = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRChart>("xrChart");
            this.xrPivotGrid = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRPivotGrid>("xrPivotGrid");
            this.pgfSalesPerson = reportInitializer.GetPivotGridField("xrPivotGrid", "pgfSalesPerson");
            this.pgfSalesTotal = reportInitializer.GetPivotGridField("xrPivotGrid", "pgfSalesTotal");
            this.pgfYear = reportInitializer.GetPivotGridField("xrPivotGrid", "pgfYear");
            this.pgfQuarter = reportInitializer.GetPivotGridField("xrPivotGrid", "pgfQuarter");
            this.xpbDevExpress = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRPictureBox>("xpbDevExpress");
            this.xpiPageCount = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRPageInfo>("xpiPageCount");
            this.xrlTitle = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("xrlTitle");

            // Parameters
            this.parameterViewType = reportInitializer.GetParameter("parameterViewType");
            this.parameterShowLabels = reportInitializer.GetParameter("parameterShowLabels");
            this.parameterGenerateSeriesFromColumns = reportInitializer.GetParameter("parameterGenerateSeriesFromColumns");
            this.parameterShowRowGrandTotals = reportInitializer.GetParameter("parameterShowRowGrandTotals");
            this.parameterShowColumnGrandTotals = reportInitializer.GetParameter("parameterShowColumnGrandTotals");

            // Data Sources
            this.sqlDataSource1 = reportInitializer.GetDataSource<DevExpress.DataAccess.Sql.SqlDataSource>("sqlDataSource1");

            // Styles
            this.OddStyle = reportInitializer.GetStyle("OddStyle");
            this.GroupHeader = reportInitializer.GetStyle("GroupHeader");
            this.EvenStyle = reportInitializer.GetStyle("EvenStyle");
            this.CategoryStyle = reportInitializer.GetStyle("CategoryStyle");
        }
        private DevExpress.XtraReports.UI.DetailBand Detail;
        private DevExpress.XtraReports.UI.BottomMarginBand BottomMargin;
        private DevExpress.XtraReports.UI.TopMarginBand topMarginBand1;
        private DevExpress.XtraReports.UI.ReportHeaderBand ReportHeader;
        private DevExpress.XtraReports.UI.XRChart xrChart;
        private DevExpress.XtraReports.UI.XRPivotGrid xrPivotGrid;
        private DevExpress.DataAccess.Sql.SqlDataSource sqlDataSource1;
        private DevExpress.XtraReports.UI.PivotGrid.XRPivotGridField pgfSalesPerson;
        private DevExpress.XtraReports.UI.PivotGrid.XRPivotGridField pgfSalesTotal;
        private DevExpress.XtraReports.UI.PivotGrid.XRPivotGridField pgfYear;
        private DevExpress.XtraReports.UI.PivotGrid.XRPivotGridField pgfQuarter;
        private DevExpress.XtraReports.UI.XRPictureBox xpbDevExpress;
        private DevExpress.XtraReports.UI.XRPageInfo xpiPageCount;
        private DevExpress.XtraReports.UI.XRLabel xrlTitle;
        private DevExpress.XtraReports.UI.XRControlStyle OddStyle;
        private DevExpress.XtraReports.UI.XRControlStyle GroupHeader;
        private DevExpress.XtraReports.UI.XRControlStyle EvenStyle;
        private DevExpress.XtraReports.UI.XRControlStyle CategoryStyle;
        private DevExpress.XtraReports.Parameters.Parameter parameterViewType;
        private DevExpress.XtraReports.Parameters.Parameter parameterShowLabels;
        private DevExpress.XtraReports.Parameters.Parameter parameterGenerateSeriesFromColumns;
        private DevExpress.XtraReports.Parameters.Parameter parameterShowRowGrandTotals;
        private DevExpress.XtraReports.Parameters.Parameter parameterShowColumnGrandTotals;
    }
}
