using DevExpress.XtraCharts;

namespace Demo.Blazor.Reports.PivotGridAndChart {
    public enum ViewTypeFiltered {
        Bar = ViewType.Bar,
        StackedBar = ViewType.StackedBar,
        FullStackedBar = ViewType.FullStackedBar,
        SideBySideStackedBar = ViewType.SideBySideStackedBar,
        SideBySideFullStackedBar = ViewType.SideBySideFullStackedBar,
        Pie = ViewType.Pie,
        Doughnut = ViewType.Doughnut,
        Funnel = ViewType.Funnel,
        Point = ViewType.Point,
        Line = ViewType.Line,
        StepLine = ViewType.StepLine,
        Spline = ViewType.Spline,
        ScatterLine = ViewType.ScatterLine,
        Area = ViewType.Area,
        SplineArea = ViewType.SplineArea,
        StackedArea = ViewType.StackedArea,
        StackedSplineArea = ViewType.StackedSplineArea,
        FullStackedArea = ViewType.FullStackedArea,
        FullStackedSplineArea = ViewType.FullStackedSplineArea,
        RadarPoint = ViewType.RadarPoint,
        RadarLine = ViewType.RadarLine,
        RadarArea = ViewType.RadarArea,
        Bar3D = ViewType.Bar3D,
        StackedBar3D = ViewType.StackedBar3D,
        FullStackedBar3D = ViewType.FullStackedBar3D,
        ManhattanBar = ViewType.ManhattanBar,
        SideBySideStackedBar3D = ViewType.SideBySideStackedBar3D,
        SideBySideFullStackedBar3D = ViewType.SideBySideFullStackedBar3D,
        Pie3D = ViewType.Pie3D,
        Doughnut3D = ViewType.Doughnut3D,
        Funnel3D = ViewType.Funnel3D,
        Line3D = ViewType.Line3D,
        StepLine3D = ViewType.StepLine3D,
        Area3D = ViewType.Area3D,
        StackedArea3D = ViewType.StackedArea3D,
        FullStackedArea3D = ViewType.FullStackedArea3D,
        Spline3D = ViewType.Spline3D,
        SplineArea3D = ViewType.SplineArea3D,
        StackedSplineArea3D = ViewType.StackedSplineArea3D,
        FullStackedSplineArea3D = ViewType.FullStackedSplineArea3D
    }
}
