using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;
using BlazorDemo.Data;

namespace BlazorDemo.DataProviders.Implementation {
    class ProductsProvider : DataProviderBase, IProductsProvider {
        readonly IList<Product> _products;

        public ProductsProvider() {
            _products = LoadInternal();
        }

        public Task<IEnumerable<Product>> LoadAsync(CancellationToken ct = default) {
            return Task.FromResult((IEnumerable<Product>)_products);
        }

        public Task RemoveAsync(Product product) {
            _products.Remove(product);
            return Task.CompletedTask;
        }

        public Task AddAsync(Product product) {
            _products.Add(product);
            return Task.CompletedTask;
        }

        static IList<Product> LoadInternal() {
            var dataSource = new List<Product>() {
                new Product() { Id = "680", Availability = false, ProductCategoryId = 14, ProductName = "HL Road Frame - Black, 58" },
                new Product() { Id = "706", Availability = true , ProductCategoryId = 14, ProductName = "HL Road Frame - Red, 58" },
                new Product() { Id = "707", Availability = false, ProductCategoryId = 31, ProductName = "Sport-100 Helmet, Red" },
                new Product() { Id = "708", Availability = true , ProductCategoryId = 31, ProductName = "Sport-100 Helmet, Black" },
                new Product() { Id = "709", Availability = false, ProductCategoryId = 23, ProductName = "Mountain Bike Socks, M" },
                new Product() { Id = "710", Availability = true , ProductCategoryId = 23, ProductName = "Mountain Bike Socks, L" },
                new Product() { Id = "711", Availability = false, ProductCategoryId = 31, ProductName = "Sport-100 Helmet, Blue" },
                new Product() { Id = "712", Availability = true , ProductCategoryId = 19, ProductName = "AWC Logo Cap" },
                new Product() { Id = "713", Availability = false, ProductCategoryId = 21, ProductName = "Long-Sleeve Logo Jersey, S" },
                new Product() { Id = "714", Availability = true , ProductCategoryId = 21, ProductName = "Long-Sleeve Logo Jersey, M" },
                new Product() { Id = "715", Availability = false, ProductCategoryId = 21, ProductName = "Long-Sleeve Logo Jersey, L" },
                new Product() { Id = "716", Availability = true , ProductCategoryId = 21, ProductName = "Long-Sleeve Logo Jersey, XL" },
                new Product() { Id = "717", Availability = false, ProductCategoryId = 14, ProductName = "HL Road Frame - Red, 62" },
                new Product() { Id = "718", Availability = true , ProductCategoryId = 14, ProductName = "HL Road Frame - Red, 44" },
                new Product() { Id = "719", Availability = false, ProductCategoryId = 14, ProductName = "HL Road Frame - Red, 48" },
                new Product() { Id = "720", Availability = true , ProductCategoryId = 14, ProductName = "HL Road Frame - Red, 52" },
                new Product() { Id = "721", Availability = false, ProductCategoryId = 14, ProductName = "HL Road Frame - Red, 56" },
                new Product() { Id = "722", Availability = true , ProductCategoryId = 14, ProductName = "LL Road Frame - Black, 58" },
                new Product() { Id = "723", Availability = false, ProductCategoryId = 14, ProductName = "LL Road Frame - Black, 60" },
                new Product() { Id = "724", Availability = true , ProductCategoryId = 14, ProductName = "LL Road Frame - Black, 62" },
                new Product() { Id = "725", Availability = false, ProductCategoryId = 14, ProductName = "LL Road Frame - Red, 44" },
                new Product() { Id = "726", Availability = true , ProductCategoryId = 14, ProductName = "LL Road Frame - Red, 48" },
                new Product() { Id = "727", Availability = false, ProductCategoryId = 14, ProductName = "LL Road Frame - Red, 52" },
                new Product() { Id = "728", Availability = true , ProductCategoryId = 14, ProductName = "LL Road Frame - Red, 58" },
                new Product() { Id = "729", Availability = false, ProductCategoryId = 14, ProductName = "LL Road Frame - Red, 60" },
                new Product() { Id = "730", Availability = true , ProductCategoryId = 14, ProductName = "LL Road Frame - Red, 62" },
                new Product() { Id = "731", Availability = false, ProductCategoryId = 14, ProductName = "ML Road Frame - Red, 44" },
                new Product() { Id = "732", Availability = true , ProductCategoryId = 14, ProductName = "ML Road Frame - Red, 48" },
                new Product() { Id = "733", Availability = false, ProductCategoryId = 14, ProductName = "ML Road Frame - Red, 52" },
                new Product() { Id = "734", Availability = true , ProductCategoryId = 14, ProductName = "ML Road Frame - Red, 58" },
                new Product() { Id = "735", Availability = false, ProductCategoryId = 14, ProductName = "ML Road Frame - Red, 60" },
                new Product() { Id = "736", Availability = true , ProductCategoryId = 14, ProductName = "LL Road Frame - Black, 44" },
                new Product() { Id = "737", Availability = false, ProductCategoryId = 14, ProductName = "LL Road Frame - Black, 48" },
                new Product() { Id = "738", Availability = true , ProductCategoryId = 14, ProductName = "LL Road Frame - Black, 52" },
                new Product() { Id = "739", Availability = false, ProductCategoryId = 12, ProductName = "HL Mountain Frame - Silver, 42" },
                new Product() { Id = "740", Availability = true , ProductCategoryId = 12, ProductName = "HL Mountain Frame - Silver, 44" },
                new Product() { Id = "741", Availability = false, ProductCategoryId = 12, ProductName = "HL Mountain Frame - Silver, 48" },
                new Product() { Id = "742", Availability = true , ProductCategoryId = 12, ProductName = "HL Mountain Frame - Silver, 46" },
                new Product() { Id = "743", Availability = false, ProductCategoryId = 12, ProductName = "HL Mountain Frame - Black, 42" },
                new Product() { Id = "744", Availability = true , ProductCategoryId = 12, ProductName = "HL Mountain Frame - Black, 44" },
                new Product() { Id = "745", Availability = false, ProductCategoryId = 12, ProductName = "HL Mountain Frame - Black, 48" },
                new Product() { Id = "746", Availability = true , ProductCategoryId = 12, ProductName = "HL Mountain Frame - Black, 46" },
                new Product() { Id = "747", Availability = false, ProductCategoryId = 12, ProductName = "HL Mountain Frame - Black, 38" },
                new Product() { Id = "748", Availability = true , ProductCategoryId = 12, ProductName = "HL Mountain Frame - Silver, 38" },
                new Product() { Id = "749", Availability = false, ProductCategoryId = 2 , ProductName = "Road-150 Red, 62" },
                new Product() { Id = "750", Availability = true , ProductCategoryId = 2 , ProductName = "Road-150 Red, 44" },
                new Product() { Id = "751", Availability = false, ProductCategoryId = 2 , ProductName = "Road-150 Red, 48" },
                new Product() { Id = "752", Availability = true , ProductCategoryId = 2 , ProductName = "Road-150 Red, 52" },
                new Product() { Id = "753", Availability = false, ProductCategoryId = 2 , ProductName = "Road-150 Red, 56" },
                new Product() { Id = "754", Availability = true , ProductCategoryId = 2 , ProductName = "Road-450 Red, 58" },
                new Product() { Id = "755", Availability = false, ProductCategoryId = 2 , ProductName = "Road-450 Red, 60" },
                new Product() { Id = "756", Availability = true , ProductCategoryId = 2 , ProductName = "Road-450 Red, 44" },
                new Product() { Id = "757", Availability = false, ProductCategoryId = 2 , ProductName = "Road-450 Red, 48" },
                new Product() { Id = "758", Availability = true , ProductCategoryId = 2 , ProductName = "Road-450 Red, 52" },
                new Product() { Id = "759", Availability = false, ProductCategoryId = 2 , ProductName = "Road-650 Red, 58" },
                new Product() { Id = "760", Availability = true , ProductCategoryId = 2 , ProductName = "Road-650 Red, 60" },
                new Product() { Id = "761", Availability = false, ProductCategoryId = 2 , ProductName = "Road-650 Red, 62" },
                new Product() { Id = "762", Availability = true , ProductCategoryId = 2 , ProductName = "Road-650 Red, 44" },
                new Product() { Id = "763", Availability = false, ProductCategoryId = 2 , ProductName = "Road-650 Red, 48" },
                new Product() { Id = "764", Availability = true , ProductCategoryId = 2 , ProductName = "Road-650 Red, 52" },
                new Product() { Id = "765", Availability = false, ProductCategoryId = 2 , ProductName = "Road-650 Black, 58" },
                new Product() { Id = "766", Availability = true , ProductCategoryId = 2 , ProductName = "Road-650 Black, 60" },
                new Product() { Id = "767", Availability = false, ProductCategoryId = 2 , ProductName = "Road-650 Black, 62" },
                new Product() { Id = "768", Availability = true , ProductCategoryId = 2 , ProductName = "Road-650 Black, 44" },
                new Product() { Id = "769", Availability = false, ProductCategoryId = 2 , ProductName = "Road-650 Black, 48" },
                new Product() { Id = "770", Availability = true , ProductCategoryId = 2 , ProductName = "Road-650 Black, 52" },
                new Product() { Id = "771", Availability = false, ProductCategoryId = 1 , ProductName = "Mountain-100 Silver, 38" },
                new Product() { Id = "772", Availability = true , ProductCategoryId = 1 , ProductName = "Mountain-100 Silver, 42" },
                new Product() { Id = "773", Availability = false, ProductCategoryId = 1 , ProductName = "Mountain-100 Silver, 44" },
                new Product() { Id = "774", Availability = true , ProductCategoryId = 1 , ProductName = "Mountain-100 Silver, 48" },
                new Product() { Id = "775", Availability = false, ProductCategoryId = 1 , ProductName = "Mountain-100 Black, 38" },
                new Product() { Id = "776", Availability = true , ProductCategoryId = 1 , ProductName = "Mountain-100 Black, 42" },
                new Product() { Id = "777", Availability = false, ProductCategoryId = 1 , ProductName = "Mountain-100 Black, 44" },
                new Product() { Id = "778", Availability = true , ProductCategoryId = 1 , ProductName = "Mountain-100 Black, 48" },
                new Product() { Id = "779", Availability = false, ProductCategoryId = 1 , ProductName = "Mountain-200 Silver, 38" },
                new Product() { Id = "780", Availability = true , ProductCategoryId = 1 , ProductName = "Mountain-200 Silver, 42" },
                new Product() { Id = "781", Availability = false, ProductCategoryId = 1 , ProductName = "Mountain-200 Silver, 46" },
                new Product() { Id = "782", Availability = true , ProductCategoryId = 1 , ProductName = "Mountain-200 Black, 38" },
                new Product() { Id = "783", Availability = false, ProductCategoryId = 1 , ProductName = "Mountain-200 Black, 42" },
                new Product() { Id = "784", Availability = true , ProductCategoryId = 1 , ProductName = "Mountain-200 Black, 46" },
                new Product() { Id = "785", Availability = false, ProductCategoryId = 1 , ProductName = "Mountain-300 Black, 38" },
                new Product() { Id = "786", Availability = true , ProductCategoryId = 1 , ProductName = "Mountain-300 Black, 40" },
                new Product() { Id = "787", Availability = false, ProductCategoryId = 1 , ProductName = "Mountain-300 Black, 44" },
                new Product() { Id = "788", Availability = true , ProductCategoryId = 1 , ProductName = "Mountain-300 Black, 48" },
                new Product() { Id = "789", Availability = false, ProductCategoryId = 2 , ProductName = "Road-250 Red, 44" },
                new Product() { Id = "790", Availability = true , ProductCategoryId = 2 , ProductName = "Road-250 Red, 48" },
                new Product() { Id = "791", Availability = false, ProductCategoryId = 2 , ProductName = "Road-250 Red, 52" },
                new Product() { Id = "792", Availability = true , ProductCategoryId = 2 , ProductName = "Road-250 Red, 58" },
                new Product() { Id = "793", Availability = false, ProductCategoryId = 2 , ProductName = "Road-250 Black, 44" },
                new Product() { Id = "794", Availability = true , ProductCategoryId = 2 , ProductName = "Road-250 Black, 48" },
                new Product() { Id = "795", Availability = false, ProductCategoryId = 2 , ProductName = "Road-250 Black, 52" },
                new Product() { Id = "796", Availability = true , ProductCategoryId = 2 , ProductName = "Road-250 Black, 58" },
                new Product() { Id = "797", Availability = false, ProductCategoryId = 2 , ProductName = "Road-550-W Yellow, 38" },
                new Product() { Id = "798", Availability = true , ProductCategoryId = 2 , ProductName = "Road-550-W Yellow, 40" },
                new Product() { Id = "799", Availability = false, ProductCategoryId = 2 , ProductName = "Road-550-W Yellow, 42" },
                new Product() { Id = "800", Availability = true , ProductCategoryId = 2 , ProductName = "Road-550-W Yellow, 44" },
                new Product() { Id = "801", Availability = false, ProductCategoryId = 2 , ProductName = "Road-550-W Yellow, 48" },
                new Product() { Id = "802", Availability = true , ProductCategoryId = 10, ProductName = "LL Fork" },
                new Product() { Id = "803", Availability = false, ProductCategoryId = 10, ProductName = "ML Fork" },
                new Product() { Id = "804", Availability = true , ProductCategoryId = 10, ProductName = "HL Fork" },
                new Product() { Id = "805", Availability = false, ProductCategoryId = 11, ProductName = "LL Headset" },
                new Product() { Id = "806", Availability = true , ProductCategoryId = 11, ProductName = "ML Headset" },
                new Product() { Id = "807", Availability = false, ProductCategoryId = 11, ProductName = "HL Headset" },
                new Product() { Id = "808", Availability = true , ProductCategoryId = 4 , ProductName = "LL Mountain Handlebars" },
                new Product() { Id = "809", Availability = false, ProductCategoryId = 4 , ProductName = "ML Mountain Handlebars" },
                new Product() { Id = "810", Availability = true , ProductCategoryId = 4 , ProductName = "HL Mountain Handlebars" },
                new Product() { Id = "811", Availability = false, ProductCategoryId = 4 , ProductName = "LL Road Handlebars" },
                new Product() { Id = "812", Availability = true , ProductCategoryId = 4 , ProductName = "ML Road Handlebars" },
                new Product() { Id = "813", Availability = false, ProductCategoryId = 4 , ProductName = "HL Road Handlebars" },
                new Product() { Id = "814", Availability = true , ProductCategoryId = 12, ProductName = "ML Mountain Frame - Black, 38" },
                new Product() { Id = "815", Availability = false, ProductCategoryId = 17, ProductName = "LL Mountain Front Wheel" },
                new Product() { Id = "816", Availability = true , ProductCategoryId = 17, ProductName = "ML Mountain Front Wheel" },
                new Product() { Id = "817", Availability = false, ProductCategoryId = 17, ProductName = "HL Mountain Front Wheel" },
                new Product() { Id = "818", Availability = true , ProductCategoryId = 17, ProductName = "LL Road Front Wheel" },
                new Product() { Id = "819", Availability = false, ProductCategoryId = 17, ProductName = "ML Road Front Wheel" },
                new Product() { Id = "820", Availability = true , ProductCategoryId = 17, ProductName = "HL Road Front Wheel" },
                new Product() { Id = "821", Availability = false, ProductCategoryId = 17, ProductName = "Touring Front Wheel" },
                new Product() { Id = "822", Availability = true , ProductCategoryId = 14, ProductName = "ML Road Frame-W - Yellow, 38" },
                new Product() { Id = "823", Availability = false, ProductCategoryId = 17, ProductName = "LL Mountain Rear Wheel" },
                new Product() { Id = "824", Availability = true , ProductCategoryId = 17, ProductName = "ML Mountain Rear Wheel" },
                new Product() { Id = "825", Availability = false, ProductCategoryId = 17, ProductName = "HL Mountain Rear Wheel" },
                new Product() { Id = "826", Availability = true , ProductCategoryId = 17, ProductName = "LL Road Rear Wheel" },
                new Product() { Id = "827", Availability = false, ProductCategoryId = 17, ProductName = "ML Road Rear Wheel" },
                new Product() { Id = "828", Availability = true , ProductCategoryId = 17, ProductName = "HL Road Rear Wheel" },
                new Product() { Id = "829", Availability = false, ProductCategoryId = 17, ProductName = "Touring Rear Wheel" },
                new Product() { Id = "830", Availability = true , ProductCategoryId = 12, ProductName = "ML Mountain Frame - Black, 40" },
                new Product() { Id = "831", Availability = false, ProductCategoryId = 12, ProductName = "ML Mountain Frame - Black, 44" },
                new Product() { Id = "832", Availability = true , ProductCategoryId = 12, ProductName = "ML Mountain Frame - Black, 48" },
                new Product() { Id = "833", Availability = false, ProductCategoryId = 14, ProductName = "ML Road Frame-W - Yellow, 40" },
                new Product() { Id = "834", Availability = true , ProductCategoryId = 14, ProductName = "ML Road Frame-W - Yellow, 42" },
                new Product() { Id = "835", Availability = false, ProductCategoryId = 14, ProductName = "ML Road Frame-W - Yellow, 44" },
                new Product() { Id = "836", Availability = true , ProductCategoryId = 14, ProductName = "ML Road Frame-W - Yellow, 48" },
                new Product() { Id = "837", Availability = false, ProductCategoryId = 14, ProductName = "HL Road Frame - Black, 62" },
                new Product() { Id = "838", Availability = true , ProductCategoryId = 14, ProductName = "HL Road Frame - Black, 44" },
                new Product() { Id = "839", Availability = false, ProductCategoryId = 14, ProductName = "HL Road Frame - Black, 48" },
                new Product() { Id = "840", Availability = true , ProductCategoryId = 14, ProductName = "HL Road Frame - Black, 52" },
                new Product() { Id = "841", Availability = false, ProductCategoryId = 22, ProductName = "Men's Sports Shorts, S" },
                new Product() { Id = "842", Availability = true , ProductCategoryId = 35, ProductName = "Touring-Panniers, Large" },
                new Product() { Id = "843", Availability = false, ProductCategoryId = 34, ProductName = "Cable Lock" },
                new Product() { Id = "844", Availability = true , ProductCategoryId = 36, ProductName = "Minipump" },
                new Product() { Id = "845", Availability = false, ProductCategoryId = 36, ProductName = "Mountain Pump" },
                new Product() { Id = "846", Availability = true , ProductCategoryId = 33, ProductName = "Taillights - Battery-Powered" },
                new Product() { Id = "847", Availability = false, ProductCategoryId = 33, ProductName = "Headlights - Dual-Beam" },
                new Product() { Id = "848", Availability = true , ProductCategoryId = 33, ProductName = "Headlights - Weatherproof" },
                new Product() { Id = "849", Availability = false, ProductCategoryId = 22, ProductName = "Men's Sports Shorts, M" },
                new Product() { Id = "850", Availability = true , ProductCategoryId = 22, ProductName = "Men's Sports Shorts, L" },
                new Product() { Id = "851", Availability = false, ProductCategoryId = 22, ProductName = "Men's Sports Shorts, XL" },
                new Product() { Id = "852", Availability = true , ProductCategoryId = 24, ProductName = "Women's Tights, S" },
                new Product() { Id = "853", Availability = false, ProductCategoryId = 24, ProductName = "Women's Tights, M" },
                new Product() { Id = "854", Availability = true , ProductCategoryId = 24, ProductName = "Women's Tights, L" },
                new Product() { Id = "855", Availability = false, ProductCategoryId = 18, ProductName = "Men's Bib-Shorts, S" },
                new Product() { Id = "856", Availability = true , ProductCategoryId = 18, ProductName = "Men's Bib-Shorts, M" },
                new Product() { Id = "857", Availability = false, ProductCategoryId = 18, ProductName = "Men's Bib-Shorts, L" },
                new Product() { Id = "858", Availability = true , ProductCategoryId = 20, ProductName = "Half-Finger Gloves, S" },
                new Product() { Id = "859", Availability = false, ProductCategoryId = 20, ProductName = "Half-Finger Gloves, M" },
                new Product() { Id = "860", Availability = true , ProductCategoryId = 20, ProductName = "Half-Finger Gloves, L" },
                new Product() { Id = "861", Availability = false, ProductCategoryId = 20, ProductName = "Full-Finger Gloves, S" },
                new Product() { Id = "862", Availability = true , ProductCategoryId = 20, ProductName = "Full-Finger Gloves, M" },
                new Product() { Id = "863", Availability = false, ProductCategoryId = 20, ProductName = "Full-Finger Gloves, L" },
                new Product() { Id = "864", Availability = true , ProductCategoryId = 25, ProductName = "Classic Vest, S" },
                new Product() { Id = "865", Availability = false, ProductCategoryId = 25, ProductName = "Classic Vest, M" },
                new Product() { Id = "866", Availability = true , ProductCategoryId = 25, ProductName = "Classic Vest, L" },
                new Product() { Id = "867", Availability = false, ProductCategoryId = 22, ProductName = "Women's Mountain Shorts, S" },
                new Product() { Id = "868", Availability = true , ProductCategoryId = 22, ProductName = "Women's Mountain Shorts, M" },
                new Product() { Id = "869", Availability = false, ProductCategoryId = 22, ProductName = "Women's Mountain Shorts, L" },
                new Product() { Id = "870", Availability = true , ProductCategoryId = 28, ProductName = "Water Bottle - 30 oz." },
                new Product() { Id = "871", Availability = false, ProductCategoryId = 28, ProductName = "Mountain Bottle Cage" },
                new Product() { Id = "872", Availability = true , ProductCategoryId = 28, ProductName = "Road Bottle Cage" },
                new Product() { Id = "873", Availability = false, ProductCategoryId = 37, ProductName = "Patch Kit/8 Patches" },
                new Product() { Id = "874", Availability = true , ProductCategoryId = 23, ProductName = "Racing Socks, M" },
                new Product() { Id = "875", Availability = false, ProductCategoryId = 23, ProductName = "Racing Socks, L" },
                new Product() { Id = "876", Availability = true , ProductCategoryId = 26, ProductName = "Hitch Rack - 4-Bike" },
                new Product() { Id = "877", Availability = false, ProductCategoryId = 29, ProductName = "Bike Wash - Dissolver" },
                new Product() { Id = "878", Availability = true , ProductCategoryId = 30, ProductName = "Fender Set - Mountain" },
                new Product() { Id = "879", Availability = false, ProductCategoryId = 27, ProductName = "All-Purpose Bike Stand" },
                new Product() { Id = "880", Availability = true , ProductCategoryId = 32, ProductName = "Hydration Pack - 70 oz." },
                new Product() { Id = "881", Availability = false, ProductCategoryId = 21, ProductName = "Short-Sleeve Classic Jersey, S" },
                new Product() { Id = "882", Availability = true , ProductCategoryId = 21, ProductName = "Short-Sleeve Classic Jersey, M" },
                new Product() { Id = "883", Availability = false, ProductCategoryId = 21, ProductName = "Short-Sleeve Classic Jersey, L" },
                new Product() { Id = "884", Availability = true , ProductCategoryId = 21, ProductName = "Short-Sleeve Classic Jersey, XL" },
                new Product() { Id = "885", Availability = false, ProductCategoryId = 16, ProductName = "HL Touring Frame - Yellow, 60" },
                new Product() { Id = "886", Availability = true , ProductCategoryId = 16, ProductName = "LL Touring Frame - Yellow, 62" },
                new Product() { Id = "887", Availability = false, ProductCategoryId = 16, ProductName = "HL Touring Frame - Yellow, 46" },
                new Product() { Id = "888", Availability = true , ProductCategoryId = 16, ProductName = "HL Touring Frame - Yellow, 50" },
                new Product() { Id = "889", Availability = false, ProductCategoryId = 16, ProductName = "HL Touring Frame - Yellow, 54" },
                new Product() { Id = "890", Availability = true , ProductCategoryId = 16, ProductName = "HL Touring Frame - Blue, 46" },
                new Product() { Id = "891", Availability = false, ProductCategoryId = 16, ProductName = "HL Touring Frame - Blue, 50" },
                new Product() { Id = "892", Availability = true , ProductCategoryId = 16, ProductName = "HL Touring Frame - Blue, 54" },
                new Product() { Id = "893", Availability = false, ProductCategoryId = 16, ProductName = "HL Touring Frame - Blue, 60" },
                new Product() { Id = "894", Availability = true , ProductCategoryId = 9 , ProductName = "Rear Derailleur" },
                new Product() { Id = "895", Availability = false, ProductCategoryId = 16, ProductName = "LL Touring Frame - Blue, 50" },
                new Product() { Id = "896", Availability = true , ProductCategoryId = 16, ProductName = "LL Touring Frame - Blue, 54" },
                new Product() { Id = "897", Availability = false, ProductCategoryId = 16, ProductName = "LL Touring Frame - Blue, 58" },
                new Product() { Id = "898", Availability = true , ProductCategoryId = 16, ProductName = "LL Touring Frame - Blue, 62" },
                new Product() { Id = "899", Availability = false, ProductCategoryId = 16, ProductName = "LL Touring Frame - Yellow, 44" },
                new Product() { Id = "900", Availability = true , ProductCategoryId = 16, ProductName = "LL Touring Frame - Yellow, 50" },
                new Product() { Id = "901", Availability = false, ProductCategoryId = 16, ProductName = "LL Touring Frame - Yellow, 54" },
                new Product() { Id = "902", Availability = true , ProductCategoryId = 16, ProductName = "LL Touring Frame - Yellow, 58" },
                new Product() { Id = "903", Availability = false, ProductCategoryId = 16, ProductName = "LL Touring Frame - Blue, 44" },
                new Product() { Id = "904", Availability = true , ProductCategoryId = 12, ProductName = "ML Mountain Frame-W - Silver, 40" },
                new Product() { Id = "905", Availability = false, ProductCategoryId = 12, ProductName = "ML Mountain Frame-W - Silver, 42" },
                new Product() { Id = "906", Availability = true , ProductCategoryId = 12, ProductName = "ML Mountain Frame-W - Silver, 46" },
                new Product() { Id = "907", Availability = false, ProductCategoryId = 6 , ProductName = "Rear Brakes" },
                new Product() { Id = "908", Availability = true , ProductCategoryId = 15, ProductName = "LL Mountain Seat/Saddle" },
                new Product() { Id = "909", Availability = false, ProductCategoryId = 15, ProductName = "ML Mountain Seat/Saddle" },
                new Product() { Id = "910", Availability = true , ProductCategoryId = 15, ProductName = "HL Mountain Seat/Saddle" },
                new Product() { Id = "911", Availability = false, ProductCategoryId = 15, ProductName = "LL Road Seat/Saddle" },
                new Product() { Id = "912", Availability = true , ProductCategoryId = 15, ProductName = "ML Road Seat/Saddle" },
                new Product() { Id = "913", Availability = false, ProductCategoryId = 15, ProductName = "HL Road Seat/Saddle" },
                new Product() { Id = "914", Availability = true , ProductCategoryId = 15, ProductName = "LL Touring Seat/Saddle" },
                new Product() { Id = "915", Availability = false, ProductCategoryId = 15, ProductName = "ML Touring Seat/Saddle" },
                new Product() { Id = "916", Availability = true , ProductCategoryId = 15, ProductName = "HL Touring Seat/Saddle" },
                new Product() { Id = "917", Availability = false, ProductCategoryId = 12, ProductName = "LL Mountain Frame - Silver, 42" },
                new Product() { Id = "918", Availability = true , ProductCategoryId = 12, ProductName = "LL Mountain Frame - Silver, 44" },
                new Product() { Id = "919", Availability = false, ProductCategoryId = 12, ProductName = "LL Mountain Frame - Silver, 48" },
                new Product() { Id = "920", Availability = true , ProductCategoryId = 12, ProductName = "LL Mountain Frame - Silver, 52" },
                new Product() { Id = "921", Availability = false, ProductCategoryId = 37, ProductName = "Mountain Tire Tube" },
                new Product() { Id = "922", Availability = true , ProductCategoryId = 37, ProductName = "Road Tire Tube" },
                new Product() { Id = "923", Availability = false, ProductCategoryId = 37, ProductName = "Touring Tire Tube" },
                new Product() { Id = "924", Availability = true , ProductCategoryId = 12, ProductName = "LL Mountain Frame - Black, 42" },
                new Product() { Id = "925", Availability = false, ProductCategoryId = 12, ProductName = "LL Mountain Frame - Black, 44" },
                new Product() { Id = "926", Availability = true , ProductCategoryId = 12, ProductName = "LL Mountain Frame - Black, 48" },
                new Product() { Id = "927", Availability = false, ProductCategoryId = 12, ProductName = "LL Mountain Frame - Black, 52" },
                new Product() { Id = "928", Availability = true , ProductCategoryId = 37, ProductName = "LL Mountain Tire" },
                new Product() { Id = "929", Availability = false, ProductCategoryId = 37, ProductName = "ML Mountain Tire" },
                new Product() { Id = "930", Availability = true , ProductCategoryId = 37, ProductName = "HL Mountain Tire" },
                new Product() { Id = "931", Availability = false, ProductCategoryId = 37, ProductName = "LL Road Tire" },
                new Product() { Id = "932", Availability = true , ProductCategoryId = 37, ProductName = "ML Road Tire" },
                new Product() { Id = "933", Availability = false, ProductCategoryId = 37, ProductName = "HL Road Tire" },
                new Product() { Id = "934", Availability = true , ProductCategoryId = 37, ProductName = "Touring Tire" },
                new Product() { Id = "935", Availability = false, ProductCategoryId = 13, ProductName = "LL Mountain Pedal" },
                new Product() { Id = "936", Availability = true , ProductCategoryId = 13, ProductName = "ML Mountain Pedal" },
                new Product() { Id = "937", Availability = false, ProductCategoryId = 13, ProductName = "HL Mountain Pedal" },
                new Product() { Id = "938", Availability = true , ProductCategoryId = 13, ProductName = "LL Road Pedal" },
                new Product() { Id = "939", Availability = false, ProductCategoryId = 13, ProductName = "ML Road Pedal" },
                new Product() { Id = "940", Availability = true , ProductCategoryId = 13, ProductName = "HL Road Pedal" },
                new Product() { Id = "941", Availability = false, ProductCategoryId = 13, ProductName = "Touring Pedal" },
                new Product() { Id = "942", Availability = true , ProductCategoryId = 12, ProductName = "ML Mountain Frame-W - Silver, 38" },
                new Product() { Id = "943", Availability = false, ProductCategoryId = 12, ProductName = "LL Mountain Frame - Black, 40" },
                new Product() { Id = "944", Availability = true , ProductCategoryId = 12, ProductName = "LL Mountain Frame - Silver, 40" },
                new Product() { Id = "945", Availability = false, ProductCategoryId = 9 , ProductName = "Front Derailleur" },
                new Product() { Id = "946", Availability = true , ProductCategoryId = 4 , ProductName = "LL Touring Handlebars" },
                new Product() { Id = "947", Availability = false, ProductCategoryId = 4 , ProductName = "HL Touring Handlebars" },
                new Product() { Id = "948", Availability = true , ProductCategoryId = 6 , ProductName = "Front Brakes" },
                new Product() { Id = "949", Availability = false, ProductCategoryId = 8 , ProductName = "LL Crankset" },
                new Product() { Id = "950", Availability = true , ProductCategoryId = 8 , ProductName = "ML Crankset" },
                new Product() { Id = "951", Availability = false, ProductCategoryId = 8 , ProductName = "HL Crankset" },
                new Product() { Id = "952", Availability = true , ProductCategoryId = 7 , ProductName = "Chain" },
                new Product() { Id = "953", Availability = false, ProductCategoryId = 3 , ProductName = "Touring-2000 Blue, 60" },
                new Product() { Id = "954", Availability = true , ProductCategoryId = 3 , ProductName = "Touring-1000 Yellow, 46" },
                new Product() { Id = "955", Availability = false, ProductCategoryId = 3 , ProductName = "Touring-1000 Yellow, 50" },
                new Product() { Id = "956", Availability = true , ProductCategoryId = 3 , ProductName = "Touring-1000 Yellow, 54" },
                new Product() { Id = "957", Availability = false, ProductCategoryId = 3 , ProductName = "Touring-1000 Yellow, 60" },
                new Product() { Id = "958", Availability = true , ProductCategoryId = 3 , ProductName = "Touring-3000 Blue, 54" },
                new Product() { Id = "959", Availability = false, ProductCategoryId = 3 , ProductName = "Touring-3000 Blue, 58" },
                new Product() { Id = "960", Availability = true , ProductCategoryId = 3 , ProductName = "Touring-3000 Blue, 62" },
                new Product() { Id = "961", Availability = false, ProductCategoryId = 3 , ProductName = "Touring-3000 Yellow, 44" },
                new Product() { Id = "962", Availability = true , ProductCategoryId = 3 , ProductName = "Touring-3000 Yellow, 50" },
                new Product() { Id = "963", Availability = false, ProductCategoryId = 3 , ProductName = "Touring-3000 Yellow, 54" },
                new Product() { Id = "964", Availability = true , ProductCategoryId = 3 , ProductName = "Touring-3000 Yellow, 58" },
                new Product() { Id = "965", Availability = false, ProductCategoryId = 3 , ProductName = "Touring-3000 Yellow, 62" },
                new Product() { Id = "966", Availability = true , ProductCategoryId = 3 , ProductName = "Touring-1000 Blue, 46" },
                new Product() { Id = "967", Availability = false, ProductCategoryId = 3 , ProductName = "Touring-1000 Blue, 50" },
                new Product() { Id = "968", Availability = true , ProductCategoryId = 3 , ProductName = "Touring-1000 Blue, 54" },
                new Product() { Id = "969", Availability = false, ProductCategoryId = 3 , ProductName = "Touring-1000 Blue, 60" },
                new Product() { Id = "970", Availability = true , ProductCategoryId = 3 , ProductName = "Touring-2000 Blue, 46" },
                new Product() { Id = "971", Availability = false, ProductCategoryId = 3 , ProductName = "Touring-2000 Blue, 50" },
                new Product() { Id = "972", Availability = true , ProductCategoryId = 3 , ProductName = "Touring-2000 Blue, 54" },
                new Product() { Id = "973", Availability = false, ProductCategoryId = 2 , ProductName = "Road-350-W Yellow, 40" },
                new Product() { Id = "974", Availability = true , ProductCategoryId = 2 , ProductName = "Road-350-W Yellow, 42" },
                new Product() { Id = "975", Availability = false, ProductCategoryId = 2 , ProductName = "Road-350-W Yellow, 44" },
                new Product() { Id = "976", Availability = true , ProductCategoryId = 2 , ProductName = "Road-350-W Yellow, 48" },
                new Product() { Id = "977", Availability = false, ProductCategoryId = 2 , ProductName = "Road-750 Black, 58" },
                new Product() { Id = "978", Availability = true , ProductCategoryId = 3 , ProductName = "Touring-3000 Blue, 44" },
                new Product() { Id = "979", Availability = false, ProductCategoryId = 3 , ProductName = "Touring-3000 Blue, 50" },
                new Product() { Id = "980", Availability = true , ProductCategoryId = 1 , ProductName = "Mountain-400-W Silver, 38" },
                new Product() { Id = "981", Availability = false, ProductCategoryId = 1 , ProductName = "Mountain-400-W Silver, 40" },
                new Product() { Id = "982", Availability = true , ProductCategoryId = 1 , ProductName = "Mountain-400-W Silver, 42" },
                new Product() { Id = "983", Availability = false, ProductCategoryId = 1 , ProductName = "Mountain-400-W Silver, 46" },
                new Product() { Id = "984", Availability = true , ProductCategoryId = 1 , ProductName = "Mountain-500 Silver, 40" },
                new Product() { Id = "985", Availability = false, ProductCategoryId = 1 , ProductName = "Mountain-500 Silver, 42" },
                new Product() { Id = "986", Availability = true , ProductCategoryId = 1 , ProductName = "Mountain-500 Silver, 44" },
                new Product() { Id = "987", Availability = false, ProductCategoryId = 1 , ProductName = "Mountain-500 Silver, 48" },
                new Product() { Id = "988", Availability = true , ProductCategoryId = 1 , ProductName = "Mountain-500 Silver, 52" },
                new Product() { Id = "989", Availability = false, ProductCategoryId = 1 , ProductName = "Mountain-500 Black, 40" },
                new Product() { Id = "990", Availability = true , ProductCategoryId = 1 , ProductName = "Mountain-500 Black, 42" },
                new Product() { Id = "991", Availability = false, ProductCategoryId = 1 , ProductName = "Mountain-500 Black, 44" },
                new Product() { Id = "992", Availability = true , ProductCategoryId = 1 , ProductName = "Mountain-500 Black, 48" },
                new Product() { Id = "993", Availability = false, ProductCategoryId = 1 , ProductName = "Mountain-500 Black, 52" },
                new Product() { Id = "994", Availability = true , ProductCategoryId = 5 , ProductName = "LL Bottom Bracket" },
                new Product() { Id = "995", Availability = false, ProductCategoryId = 5 , ProductName = "ML Bottom Bracket" },
                new Product() { Id = "996", Availability = true , ProductCategoryId = 5 , ProductName = "HL Bottom Bracket" },
                new Product() { Id = "997", Availability = false, ProductCategoryId = 2 , ProductName = "Road-750 Black, 44" },
                new Product() { Id = "998", Availability = true , ProductCategoryId = 2 , ProductName = "Road-750 Black, 48" },
                new Product() { Id = "999", Availability = false, ProductCategoryId = 2 , ProductName = "Road-750 Black, 52" },
            };
            return dataSource;
        }
    }
}
