//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlazorDemo.Reports.ReportMerging {
    
    public partial class ChartReport : DevExpress.XtraReports.UI.XtraReport {
        private void InitializeComponent() {
            DevExpress.XtraReports.ReportInitializer reportInitializer = new DevExpress.XtraReports.ReportInitializer(this, "BlazorDemo.Reports.ReportMerging.ChartReport.repx");

            // Controls
            this.Detail = reportInitializer.GetControl<DevExpress.XtraReports.UI.DetailBand>("Detail");
            this.BottomMargin = reportInitializer.GetControl<DevExpress.XtraReports.UI.BottomMarginBand>("BottomMargin");
            this.ReportHeader = reportInitializer.GetControl<DevExpress.XtraReports.UI.ReportHeaderBand>("ReportHeader");
            this.topMarginBand1 = reportInitializer.GetControl<DevExpress.XtraReports.UI.TopMarginBand>("topMarginBand1");
            this.xrChart1 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRChart>("xrChart1");
            this.xrlblCategoryName = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("xrlblCategoryName");
            this.xrPictureBox4 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRPictureBox>("xrPictureBox4");
            this.xrPageInfo1 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRPageInfo>("xrPageInfo1");
            this.xrLine1 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLine>("xrLine1");
            this.lbTitle = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("lbTitle");
            this.xrPageInfo2 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRPageInfo>("xrPageInfo2");

            // Parameters
            this.AppearanceParameter = reportInitializer.GetParameter("AppearanceParameter");
            this.ColorEachParameter = reportInitializer.GetParameter("ColorEachParameter");
            this.ShowTitle = reportInitializer.GetParameter("ShowTitle");
            this.LowCategory = reportInitializer.GetParameter("LowCategory");
            this.HighCategory = reportInitializer.GetParameter("HighCategory");

            // Data Sources
            this.sqlDataSource1 = reportInitializer.GetDataSource<DevExpress.DataAccess.Sql.SqlDataSource>("sqlDataSource1");

            // Styles
            this.OddStyle = reportInitializer.GetStyle("OddStyle");
            this.GroupHeader = reportInitializer.GetStyle("GroupHeader");
            this.EvenStyle = reportInitializer.GetStyle("EvenStyle");
            this.CategoryStyle = reportInitializer.GetStyle("CategoryStyle");
        }
        private DevExpress.XtraReports.UI.DetailBand Detail;
        private DevExpress.XtraReports.UI.BottomMarginBand BottomMargin;
        private DevExpress.XtraReports.UI.ReportHeaderBand ReportHeader;
        private DevExpress.XtraReports.UI.TopMarginBand topMarginBand1;
        private DevExpress.XtraReports.UI.XRChart xrChart1;
        private DevExpress.XtraReports.UI.XRLabel xrlblCategoryName;
        private DevExpress.XtraReports.UI.XRPictureBox xrPictureBox4;
        private DevExpress.XtraReports.UI.XRPageInfo xrPageInfo1;
        private DevExpress.XtraReports.UI.XRLine xrLine1;
        private DevExpress.XtraReports.UI.XRLabel lbTitle;
        private DevExpress.XtraReports.UI.XRPageInfo xrPageInfo2;
        private DevExpress.DataAccess.Sql.SqlDataSource sqlDataSource1;
        private DevExpress.XtraReports.UI.XRControlStyle OddStyle;
        private DevExpress.XtraReports.UI.XRControlStyle GroupHeader;
        private DevExpress.XtraReports.UI.XRControlStyle EvenStyle;
        private DevExpress.XtraReports.UI.XRControlStyle CategoryStyle;
        private DevExpress.XtraReports.Parameters.Parameter AppearanceParameter;
        private DevExpress.XtraReports.Parameters.Parameter ColorEachParameter;
        private DevExpress.XtraReports.Parameters.Parameter ShowTitle;
        private DevExpress.XtraReports.Parameters.Parameter LowCategory;
        private DevExpress.XtraReports.Parameters.Parameter HighCategory;
    }
}
