//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlazorDemo.Reports.Shape {
    
    public partial class Report : DevExpress.XtraReports.UI.XtraReport {
        private void InitializeComponent() {
            DevExpress.XtraReports.ReportInitializer reportInitializer = new DevExpress.XtraReports.ReportInitializer(this, "BlazorDemo.Reports.Shape.Report.repx");

            // Controls
            this.Detail = reportInitializer.GetControl<DevExpress.XtraReports.UI.DetailBand>("Detail");
            this.ReportHeader = reportInitializer.GetControl<DevExpress.XtraReports.UI.ReportHeaderBand>("ReportHeader");
            this.topMarginBand1 = reportInitializer.GetControl<DevExpress.XtraReports.UI.TopMarginBand>("topMarginBand1");
            this.bottomMarginBand1 = reportInitializer.GetControl<DevExpress.XtraReports.UI.BottomMarginBand>("bottomMarginBand1");
            this.xrShape28 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRShape>("xrShape28");
            this.xrShape27 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRShape>("xrShape27");
            this.xrShape26 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRShape>("xrShape26");
            this.xrShape25 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRShape>("xrShape25");
            this.xrShape24 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRShape>("xrShape24");
            this.xrShape23 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRShape>("xrShape23");
            this.xrShape22 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRShape>("xrShape22");
            this.xrShape21 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRShape>("xrShape21");
            this.xrShape20 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRShape>("xrShape20");
            this.xrShape19 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRShape>("xrShape19");
            this.xrShape18 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRShape>("xrShape18");
            this.xrShape17 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRShape>("xrShape17");
            this.xrShape16 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRShape>("xrShape16");
            this.xrShape15 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRShape>("xrShape15");
            this.xrShape14 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRShape>("xrShape14");
            this.xrShape13 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRShape>("xrShape13");
            this.xrShape12 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRShape>("xrShape12");
            this.xrShape11 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRShape>("xrShape11");
            this.xrShape10 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRShape>("xrShape10");
            this.xrShape9 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRShape>("xrShape9");
            this.xrShape8 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRShape>("xrShape8");
            this.xrShape7 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRShape>("xrShape7");
            this.xrShape6 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRShape>("xrShape6");
            this.xrShape5 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRShape>("xrShape5");
            this.xrShape4 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRShape>("xrShape4");
            this.xrShape3 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRShape>("xrShape3");
            this.xrShape2 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRShape>("xrShape2");
            this.xrShape1 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRShape>("xrShape1");
            this.xrLabel1 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("xrLabel1");
        }
        private DevExpress.XtraReports.UI.DetailBand Detail;
        private DevExpress.XtraReports.UI.ReportHeaderBand ReportHeader;
        private DevExpress.XtraReports.UI.TopMarginBand topMarginBand1;
        private DevExpress.XtraReports.UI.BottomMarginBand bottomMarginBand1;
        private DevExpress.XtraReports.UI.XRShape xrShape28;
        private DevExpress.XtraReports.UI.XRShape xrShape27;
        private DevExpress.XtraReports.UI.XRShape xrShape26;
        private DevExpress.XtraReports.UI.XRShape xrShape25;
        private DevExpress.XtraReports.UI.XRShape xrShape24;
        private DevExpress.XtraReports.UI.XRShape xrShape23;
        private DevExpress.XtraReports.UI.XRShape xrShape22;
        private DevExpress.XtraReports.UI.XRShape xrShape21;
        private DevExpress.XtraReports.UI.XRShape xrShape20;
        private DevExpress.XtraReports.UI.XRShape xrShape19;
        private DevExpress.XtraReports.UI.XRShape xrShape18;
        private DevExpress.XtraReports.UI.XRShape xrShape17;
        private DevExpress.XtraReports.UI.XRShape xrShape16;
        private DevExpress.XtraReports.UI.XRShape xrShape15;
        private DevExpress.XtraReports.UI.XRShape xrShape14;
        private DevExpress.XtraReports.UI.XRShape xrShape13;
        private DevExpress.XtraReports.UI.XRShape xrShape12;
        private DevExpress.XtraReports.UI.XRShape xrShape11;
        private DevExpress.XtraReports.UI.XRShape xrShape10;
        private DevExpress.XtraReports.UI.XRShape xrShape9;
        private DevExpress.XtraReports.UI.XRShape xrShape8;
        private DevExpress.XtraReports.UI.XRShape xrShape7;
        private DevExpress.XtraReports.UI.XRShape xrShape6;
        private DevExpress.XtraReports.UI.XRShape xrShape5;
        private DevExpress.XtraReports.UI.XRShape xrShape4;
        private DevExpress.XtraReports.UI.XRShape xrShape3;
        private DevExpress.XtraReports.UI.XRShape xrShape2;
        private DevExpress.XtraReports.UI.XRShape xrShape1;
        private DevExpress.XtraReports.UI.XRLabel xrLabel1;
    }
}
